#!/bin/bash

# Music info

status="$(playerctl status)"
artist=$(playerctl metadata artist 2>/dev/null)
title=$(playerctl metadata title 2>/dev/null)

if [[ $status == *"[playing]"* ]]; then
	play_pause=""
else
	play_pause=""
fi
echo "$play_pause $artist - $title"
